.\" Copyright 1999 Frodo Looijaard <frodol@dds.nl>
.\" sensors is distributed under the GPL
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.TH sensors 1  "October 2006" "" "Linux User's Manual"
.SH NAME
sensors \- print sensors information
.SH SYNOPSIS
.B sensors [
.I options
.B ] [
.I chips
.B ]
.br
.B sensors -s [
.I chips
.B ]

.SH DESCRIPTION
.B sensors
is used to show the current readings of all sensor chips.
.br
.B sensors -s
is used to set all limits as specified in the configuration file.

.B sensors
knows about certain chips, and outputs nicely formatted readings for them; but
it can also display the information of unknown chips, as long as 
.I libsensors
knows about them.

.SH OPTIONS
.IP "-c config-file"
Specify a configuration file. If no file is specified, `/etc/sensors.conf'
is used. Use `-c /dev/null' to temporarily disable this default configuration
file.
.IP -h
Print a help text and exit.
.IP -s
Evaluate all `set' statements in the configuration file and exit. You must
be `root' to do this. If this parameter is not specified, no `set' statement
is evaluated.
.IP -A
Do not show the adapter for each chip.
.IP -U
Hide unknown chips.
.IP -u
Treat all chips as unknown ones. Output will be of much lower quality;
this option is only added for testing purposes.
.IP -v
Print the program version and exit.
.IP -f
Print the temperatures in degrees Fahrenheit instead of Celsius.
.SH FILES
.I /etc/sensors.conf
.RS
The system wide configuration file. See
.BR sensors.conf (5)
for further details.
.RE
.SH "CONFORMING TO"
lm_sensors-2.x
.SH SEE ALSO
sensors.conf(5)

.SH AUTHOR
Frodo Looijaard and the lm_sensors group
http://www.lm-sensors.org/


