.TH I2CDETECT 8 "March 2004"
.SH NAME
i2cdetect \- detect I\u2\dC chips

.SH SYNOPSIS
.B i2cdetect
.RI [ -f ]
.RI [ -q | -r ]
.I i2cbus
.br
.B i2cdetect
.I -l

.SH DESCRIPTION
i2cdetect is a userspace program to scan an I\u2\dC bus for devices. It
outputs a table with the list of detected devices on the specified bus.
\fIi2cbus\fR indicates the number of the I\u2\dC bus to be scanned, and
should correspond to one of the busses listed by \fIi2cdetect -l\fR.

.SH WARNING
This program can confuse your I\u2\dC bus, cause data loss and worse!

.SH OPTIONS
.TP
.B "\-f"
Force scanning of non-regular addresses. Not recommended.
.TP
.B "\-q"
Use SMBus "quick write" commands for probing (by default, the command
used is the one believed to be the safest for each address). 
Not recommended. This is known to corrupt the Atmel AT24RF08 EEPROM
found on many IBM Thinkpad laptops.
.TP
.B "\-r"
Use SMBus "read byte" commands for probing (by default, the command
used is the one believed to be the safest for each address). 
Not recommended. This is known to lock SMBus on various write-only
chips (most notably clock chips at address 0x69).
.TP
.B "\-l"
Output a list of installed busses.

.SH CONFORMING TO
lm_sensors-2.x

.SH SEE ALSO
i2cdump(8), sensors-detect(8)

.SH AUTHOR
Frodo Looijaard, Mark D. Studebaker, and the lm_sensors group
http://www.lm-sensors.nu/
This manual page was written by Aurelien Jarno <aurel32@debian.org>, for
the Debian GNU/Linux system. It was then reviewed by the lm_sensors team and
is now part of the lm_sensors source distribution.
