.TH SENSORS-DETECT 8 "March 2004"
.SH NAME
sensors-detect \- detect hardware monitoring chips

.SH SYNOPSIS
.B sensors-detect

.SH DESCRIPTION
sensors-detect is an interactive program that will walk you through the
process of scanning your system for various hardware monitoring chips,
or sensors, supported by libsensors(3), or more generally by the lm_sensors
tool suite.

.SH CONFORMING TO
lm_sensors-2.x

.SH SEE ALSO
sensors(1), libsensors(3), i2cdetect(8)

.SH AUTHOR
Frodo Looijaard and the lm_sensors group
http://www.lm-sensors.nu/
This manual page was written by Joey Hess <joey@debian.org>, for
the Debian GNU/Linux system. It was then reviewed by the lm_sensors team and
is now part of the lm_sensors source distribution.
