#!/bin/sh
#
# edit a ticket
#
if [ $# -ne 1 ]
then
	echo usage: $0 ticketnumber
	exit 1
fi
#
exec netscape -remote "openURL(https://secure.netroedge.com/~lm78/secure_support/editticket.cgi?ticket=$1)"
